name: Generate New Tag and Release on Push to Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate new tag
        id: generate_tag
        run: |
          git fetch --all
          latest_tag=$(git describe --tags --abbrev=0)
          new_tag=$(semver bump $latest_tag)
          git tag $new_tag

      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.generate_tag.outputs.new_tag }}
          name: ${{ steps.generate_tag.outputs.new_tag }}
          body: ${{ steps.generate_tag.outputs.changelog }}